### ISSUE TITLE
returns internal server error if an incorrect group is provided

### ISSUE THREAD

**Issue by Seiterle** [pfadiflamberg/billy#17]
When creating a new bulk with an invalid group id an internal server error is returned, instead of an invalid argument error. 

e.g. the following command returns an internal server error

```
curl -v --request POST \
  --url http://127.0.0.1:5000/bulk \
  --header 'Content-Type: application/json' \
  --data '{"title":"Test","group":"234777777777777"}'
  ```

**Comment by nicoberling** [comment]
Added error handling for various errors, including missing parameters in #18
